lib/clovercms/articulate/config/routes.rb
Rails.application.routes.draw do
  namespace :dashboard do
    resources :articles, :only => [ :index, :edit, :new, :update, :create, :destroy ]
  end
end

lib/clovercms/articulate/app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :title, :body, :publish_date
  validates_length_of :body, :minimum => 50
  validates :publish_date, :date => { :after_or_equal_to => lambda { | date | Date.today } }
  scope :published, where([ 'published = ?', true ])

  def to_param
    if title.present?
      "#{id}-#{title.parameterize}"
    else
      id.to_s
    end
  end
end

lib/clovercms/articulate/app/controllers/dashboard/articles_controller.rb
class Dashboard::ArticlesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_article, :only => [ :edit, :update, :destroy ]

  set_tab :list_articles,  :only => :index
  set_tab :new_article,   :only => :new

  access_control do
    allow :admin
    allow :editor,  :to => [ :new, :create, :index ]
    allow :owner,   :of => :article, :to => [ :edit, :update, :destroy ]
  end

  def index
    @articles = Article.page params[:page]
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build params[:article]

    if @article.save
      flash[:success] = t 'messages.notifications.success'
      current_user.has_role! :owner, @article
      redirect_to edit_dashboard_article_path(@article)
    else
      render :new
    end
  end

  def update
    if @article.update_attributes( params[:article] )
      flash[:success] = t 'messages.notifications.success'
      redirect_to edit_dashboard_article_path( @article )
    else
      render :edit
    end
  end

  def destroy
    if @article.delete
      flash[:success] = t 'messages.notifications.success'
    else
      flash[:error]   = t 'messages.notifications.error'
    end

    redirect_to dashboard_articles_path
  end

  private
  def set_article
    @article = Article.find params[:id]
  end
end

lib/clovercms/articulate/app/views/dashboard/articles/_article.html.erb
<fieldset>
  <%= form_for [ :dashboard, article ], :validate => true do |f| %>
    <%= render "shared/error_messages", :target => @article %>

    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :body %>
    <%= f.text_area :body, :class => 'wymeditor' %>

    <%= f.label :publish_date %>
    <div class="grouped_selector"><%= f.date_select :publish_date, :start_year => Time.now.year %></div>

    <%= f.label :published %>
    <div class="publish_article"><%= f.check_box :published,   :class => :published %>

    <%= f.submit :class => 'wymupdate' %>
  <% end %>
</fieldset>

lib/clovercms/articulate/app/views/dashboard/articles/edit.html.erb
<%= render @article %>

lib/clovercms/articulate/app/views/dashboard/articles/index.html.erb
<p class="info">
  <span class="bold"><%= t 'messages.labels.information' %></span>
  <%= t '.info' %>
</p>

<table class="tabular" cellpadding="0" cellspacing="0">
  <thead>
    <tr>
      <th><%= t 'activerecord.attributes.article.title' %></th>
      <th><%= t 'activerecord.attributes.article.publish_date' %></th>
      <th><%= t 'messages.labels.operations' %></th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr class="<%= cycle(:odd, :even) %>">
        <td><%= link_to article.title, edit_dashboard_article_path(article) %></td>
        <td><%= article.publish_date %></td>
        <td>
          <%= link_to t('links.edit'), edit_dashboard_article_path(article) %>
          |
          <%= link_to t('links.destroy'), dashboard_article_path(article), :method => :delete, :confirm => t('messages.confirmations.are_you_sure') %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to t('links.new'), new_dashboard_article_path %>
|
<%= paginate @articles %>

lib/clovercms/articulate/app/views/dashboard/articles/new.html.erb
<%= render @article %>

lib/clovercms/articulate/app/views/layouts/dashboard/nav/_articles.html.erb
<%= tabs_tag :open_tabs => { :id => "sub_menu", :class => "sub_nav" } do |tab| %>
  <%= tab.list_articles  t('links.list'), dashboard_articles_path %>
  <%= tab.new_article    t('links.new'), new_dashboard_article_path %>
<% end %>